name: Unit Tests (Lab03)
on:
  push:
    paths:
      - 'Lab03/CollisionComponent.cpp'
jobs:
  runtest:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Build and run tests
        run: bash tests.sh -xe
        env:
          LAB_TO_TEST: Lab03
